//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gmbdb
{
    using System;
    
    public partial class CommentToReview
    {
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public Guid ReviewId { get; set; }
        public string Comment { get; set; }
        public DateTime CreatedDate { get; set; }
        public virtual Review Review { get; set; }
        public virtual User User { get; set; }

        public CommentToReview()
        {
            CreatedDate = DateTime.Today;
            Id = new Guid();
        }
    }
}
